services:
  app:
    container_name: game_backend_app
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/game_backend
    ports:
      - "4000:4000"
      - "4100:4100"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    working_dir: /app
    command: ["bash", "-c", "mix ecto.reset && mix phx.server"]

  postgres:
    container_name: game_backend_db
    image: postgres:16.1
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=game_backend
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - game_backend_data:/var/lib/postgresql/data/

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
     - 9100:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  game_backend_data:
  grafana_data:
